spring:
  application:
    name: academic-system
  datasource:
    url: jdbc:mysql://localhost:3306/academic_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .ftl
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.academicsystem.entity

server:
  port: 8080

logging:
  level:
    com.example.academicsystem: INFO
